name: telemedicine_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  http: ^1.2.2
  provider: ^6.1.2
  flutter_local_notifications: ^18.0.1
  video_player: ^2.9.2
  cupertino_icons: ^1.0.8
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets section to include your images
  assets:
    - assets/images/hospital1.jpg
    - assets/images/hospital2.jpg
    - assets/images/hospital3.jpg
    - assets/images/hospital_logo.png
    - assets/images/user_avatar.png
    - assets/images/mental_health.png
    - assets/images/nutrition.png
    - assets/images/fitness.png
    - assets/images/doctor1.png
    - assets/images/doctor2.png
    - assets/images/doctor3.png
